# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4728ca0cbd1cd333b39358b436fc405b8134349250b3340ea708309b4362783779a5510203c782fe63f8cf537b5aef86a893422cc1f8d5a0e67a58e2052b5e99

test:
  secret_key_base: b176bcfed5e1e146221c866abae9e3f96c195b0434d5e3058154389b379743499136716f03d12bf74bf42d57227dfc49b014697ef72942aaa93cd97cbcc313f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
